---

#
# QEMU
#
# This task installs QEMU and associated packages
#

# Install qemu/libvirt if the install_qemu variable is true
- name: Install QEMU and Libvirt
  when: install_qemu
  block:

    - name: Install QEMU
      ansible.builtin.dnf:
        name:
          - bridge-utils
          - coreutils
          - edk2-tools
          - genisoimage
          - grep
          - guestfs-tools
          - jq
          - libguestfs-tools
          - libvirt
          - libvirt-devel
          - lsb
          - procps
          - qemu
          - qemu-kvm
          - spice-gtk-tools
          - swtpm
          - usbutils
          - util-linux
          - virt-install
          - virt-manager
          - virt-top
          - virt-viewer
          - xdg-user-dirs
          - xrandr
          - unzip
        state: present
        update_cache: true
