---

#
# Sonic 3 AIR
#
# This task installs the Flatpak version of Sonic 3 AIR
# https://flathub.org/apps/org.sonic3air.Sonic3AIR
#

# Install Sonic 3 AIR flatpak if the install_sonic3air_flatpak variable is true
- name: Install Sonic 3 AIR Kart flatpak
  when: install_sonic3air_flatpak
  block:

    - name: Install the Sonic 3 AIR flatpak from flathub
      community.general.flatpak:
        name: org.sonic3air.Sonic3AIR
        state: present
