---

#
# requirements
#
# This defines the requirements for the playbook
#

# We need the community.general galaxy collection for this playbook
# in order to install flatpaks and add copr repos
collections:
  - name: community.general
  - name: ansible.posix
