---

#
# setup-workstation.yml
#
# This playbook sets up the local Fedora system to my specifications.
#

- name: Run setup-workstation playbook
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
    - selinux
    - firewalld
    - install-packages
    - extra-packages
    - autofs
    - asus-laptop
  vars:
    # Set SELinux to permissive?
    selinux_permissive: false

    # Disable firewalld?
    disable_firewalld: false

    # Install ProtonUp-QT flatpak?
    install_protonup: false

    # Install Steam RPM package?
    install_steam: false

    # Install Mangohud performance overlay RPM package?
    install_mangohud: false

    # Install Chrome RPM package?
    install_chrome: false

    # Install Thunderbird?
    install_thunderbird: false

    # Install VSCode RPM package?
    install_vscode: false

    # Install KeepassXC RPM package?
    install_keepassxc: false

    # Install AMD Ryzen Zenpower kernel module?
    install_zenpower: false

    # Install Corectrl performance tuning utility?
    install_corectrl: false

    # Install Kdiskmark disk benchmarking utility?
    install_kdiskmark: false

    # Install the Solaar mouse configuration tool?
    install_solaar: false

    # Install QEMU and Libvirt virtualization tools?
    install_qemu: false

    # Install GZDoom?
    install_gzdoom: false

    # Install dsda-doom?
    install_dsdadoom: false

    # Configure Synology and Freenas autofs shares?
    # If yes, set the IPs of the NAS devices
    configure_autofs_shares: false
    synology_ip:
    freenas_ip:

    # Install Asus linux laptop stuff?
    install_asus_linux: false
