---

#
# setup-workstation.yml
#
# This playbook sets up the local Fedora system to my specifications.
#

- name: Run setup-workstation playbook
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
    - selinux
    - firewalld
    - install-packages
    - flathub
    - steam
    - protonup
    - mangohud
    - heroic
    - lutris
    - ludusavi
    - gzdoom
    - dsda-doom
    - openrct2
    - retroarch
    - duckstation
    - sonic3air
    - srb2
    - srb2-kart
    - discord
    - chrome
    - chromium
    - corectrl
    - freetube
    - warehouse
    - gearlever
    - handbrake
    - makemkv
    - kdiskmark
    - keepassxc
    - obs
    - qemu
    - solaar
    - thunderbird
    - vlc
    - vscode
    - vscodium
    - zenpower
    - autofs
    - asus-laptop
  vars:
    ############################
    ######     Gaming     ######
    ############################

    ######    Flatpaks    ######

    # Install ProtonUp-QT flatpak?
    install_protonup: false

    # Install Steam flatpak?
    install_steam_flatpak: false

    # Install Mangohud performance overlay flatpak?
    install_mangohud_flatpak: false

    # Install Heroic Games Launcher flatpak?
    install_heroic_flatpak: false

    # Install Lutris flatpak?
    install_lutris_flatpak: false

    # Install Ludusavi game save backup utility flatpak?
    install_ludusavi_flatpak: false

    # Install GZDoom flatpak?
    install_gzdoom_flatpak: false

    # Install OpenRCT2 flatpak?
    install_openrct2_flatpak: false

    # Install Retroarch flatpak?
    install_retroarch_flatpak: false

    # Install Duckstation flatpak?
    install_duckstation_flatpak: false

    # Install Sonic Robo Blast 2 flatpak?
    install_srb2_flatpak: false

    # Install Sonic Robo Blast 2 Kart flatpak?
    install_srb2kart_flatpak: false

    # Install Sonic 3 AIR flatpak?
    install_sonic3air_flatpak: false

    ######      RPMs      ######

    # Install Steam RPM package?
    install_steam: false

    # Install Mangohud performance overlay RPM package?
    install_mangohud: false

    # Install Heroic Games Launcher RPM package?
    install_heroic: false

    # Install Lutris RPM package?
    install_lutris: false

    # Install GZDoom RPM package?
    install_gzdoom: false

    # Install dsda-doom RPM package?
    install_dsdadoom: false


    ############################
    ######      Misc      ######
    ############################

    ######    Flatpaks    ######

    # Install Discord flatpak?
    install_discord_flatpak: false

    # Install Chrome flatpak?
    install_chrome_flatpak: false

    # Install Chromium flatpak?
    install_chromium_flatpak: false

    # Install Thunderbird flatpak?
    install_thunderbird_flatpak: false

    # Install VSCode flatpak?
    install_vscode_flatpak: false

    # Install VSCodium flatpak?
    install_vscodium_flatpak: false

    # Install KeepassXC flatpak?
    install_keepassxc_flatpak: false

    # Install Handbrake flatpak?
    install_handbrake_flatpak: false

    # Install MakeMKV flatpak?
    install_makemkv_flatpak: false

    # Install OBS Studio flatpak?
    install_obs_flatpak: false

    # Install VLC flatpak?
    install_vlc_flatpak: false

    # Install Freetube flatpak?
    install_freetube_flatpak: false

    # Install Warehouse flatpak?
    install_warehouse_flatpak: false

    # Install Gear Lever flatpak?
    install_gearlever_flatpak: false

    ######      RPMs      ######

    # Install Chrome RPM package?
    install_chrome: false

    # Install Chromium RPM Package?
    install_chromium: false

    # Install Thunderbird RPM package?
    install_thunderbird: false

    # Install VSCode RPM package?
    install_vscode: false

    # Install VSCodium RPM package?
    install_vscodium: false

    # Install KeepassXC RPM package?
    install_keepassxc: false

    # Install Handbrake RPM package?
    install_handbrake: false


    ############################
    ###### System Configs ######
    ############################

    # Install some basic packages?
    install_basic_packages: false

    # Set SELinux to permissive?
    selinux_permissive: false

    # Disable firewalld?
    disable_firewalld: false

    # Install AMD Ryzen Zenpower kernel module?
    install_zenpower: false

    # Install Corectrl performance tuning utility?
    install_corectrl: false

    # Install Kdiskmark disk benchmarking utility?
    install_kdiskmark: false

    # Install the Solaar mouse configuration tool?
    install_solaar: false

    # Install QEMU and Libvirt virtualization tools?
    install_qemu: false

    # Configure Synology and Freenas autofs shares?
    # If yes, set the IPs of the NAS devices
    configure_autofs_shares: false
    synology_ip:
    freenas_ip:

    # Install Asus linux laptop stuff?
    # https://asus-linux.org/wiki/fedora-guide/
    install_asus_linux: false
