---

#
# setup-workstation.yml
#
# This playbook sets up the local Fedora system to my specifications.
#

- name: Run setup-workstation playbook
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
    - install-packages
    - extra-packages
    - autofs
    - asus-laptop
  vars:
    # Install Asus linux laptop stuff?
    install_asus_linux: false

    # Install Steam?
    install_steam: false

    # Install Mangohud Performance Overlay?
    install_mangohud: false

    # Install Chrome?
    install_chrome: false

    # Install Microsoft Edge?
    install_edge: false

    # Install VSCode?
    install_vscode: false

    # Install VSCodium?
    install_vscodium: false

    # Install AMD Ryzen Zenpower Module?
    install_zenpower: false

    # Install the Solaar mouse configuration tool?
    install_solaar: false

    # Install KeepassXC?
    install_keepassxc: false

    # Install QEMU and Libvirt?
    install_qemu: false

    # Install GZDoom?
    install_gzdoom: false

    # Install dsda-doom?
    install_dsdadoom: false

    # Configure Synology and Freenas autofs shares?
    # If yes, set the IPs of the NAS devices
    configure_autofs_shares: false
    synology_ip:
    freenas_ip:
