---

#
# Retroarch
#
# This task installs the Flatpak version of Retroarch
# https://flathub.org/apps/org.libretro.RetroArch
#

# Install Retroarch flatpak if the install_retroarch_flatpak variable is true
- name: Install Retroarch flatpak
  when: install_retroarch_flatpak
  block:

    - name: Install the Retroarch flatpak from flathub
      community.general.flatpak:
        name: org.libretro.RetroArch
        state: present
