---

#
# GZDoom
#
# This task installs either the RPM or Flatpak version of GZDoom
#

# Install gzdoom if the install_gzdoom variable is true
- name: Install GZDoom
  when: install_gzdoom
  block:

    - name: Enable gzdoom copr repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        name: nalika/gzdoom
        state: enabled

    - name: Install gzdoom
      ansible.builtin.dnf:
        name:
          - gzdoom
        state: present
        update_cache: true

# https://flathub.org/apps/org.zdoom.GZDoom
# Install gzdoom flatpak if the install_gzdoom_flatpak variable is true
- name: Install GZDoom flatpak
  when: install_gzdoom_flatpak
  block:

    - name: Install the GZDoom flatpak from flathub
      community.general.flatpak:
        name: org.zdoom.GZDoom
        state: present
