---

#
# KeepassXC
#
# This task installs either the RPM or Flatpak version of KeepassXC
# https://flathub.org/apps/org.keepassxc.KeePassXC
#

# Install keepassxc if the install_keepassxc variable is true
- name: Install KeepassXC
  when: install_keepassxc
  block:

    - name: Install keepassxc
      ansible.builtin.dnf:
        name:
          - keepassxc
        state: present
        update_cache: true

# Install KeepassXC flatpak if the install_keepassxc_flatpak variable is true
- name: Install KeepassXC flatpak
  when: install_keepassxc_flatpak
  block:

    - name: Install the KeepassXC flatpak from flathub
      community.general.flatpak:
        name: org.keepassxc.KeePassXC
        state: present
