---

#
# Handbrake
#
# This task installs either the RPM or Flatpak version of Handbrake
#

# Install handbrake if the install_handbrake variable is true
- name: Install Handbrake
  when: install_handbrake
  block:

    - name: Install handbrake
      ansible.builtin.dnf:
        name:
          - handbrake
          - handbrake-gui
        state: present
        update_cache: true

# https://flathub.org/apps/fr.handbrake.ghb
# Install Handbrake flatpak if the install_handbrake_flatpak variable is true
- name: Install Handbrake flatpak
  when: install_handbrake_flatpak
  block:

    - name: Install the Handbrake flatpak from flathub
      community.general.flatpak:
        name: fr.handbrake.ghb
        state: present
