---

#
# Warehouse
#
# This task installs the Warehouse flatpak
# https://flathub.org/apps/io.github.flattool.Warehouse
#


# Install Warehouse flatpak if the install_warehouse_flatpak variable is true
- name: Install Warehouse flatpak
  when: install_warehouse_flatpak
  block:

    - name: Install the Warehouse flatpak from flathub
      community.general.flatpak:
        name: io.github.flattool.Warehouse
        state: present
