---

#
# Heroic Games Launcher
#
# This task installs the Flatpak version Heroic Games Launcher
#

# Install Heroic flatpak if the install_heroic_flatpak variable is true
- name: Install Heroic flatpak
  when: install_heroic_flatpak
  block:

    - name: Install the Heroic flatpak from flathub
      community.general.flatpak:
        name: com.heroicgameslauncher.hgl
        state: present
