---

#
# flathub
#
# This task enabled the flathub flatpak repo
#

# Adding the flathub repo in this way seems to be broken at the moment
# https://stackoverflow.com/questions/73090882/ansible-added-flathub-repo-isnt-recognized
# https://github.com/ansible-collections/community.general/issues/3118
# - name: Add the flathub flatpak repository
#   community.general.flatpak_remote:
#     name: flathub
#     flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
#     method: system
#     state: present

- name: Add flathub repo manually
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install the Flatseal flatpak from flathub
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    state: present
