---

#
# OBS
#
# This task installs the Flatpak version of OBS
#

# Install OBS flatpak if the install_obs variable is true
- name: Install OBS flatpak
  when: install_obs_flatpak
  block:

    - name: Install the OBS Studio flatpak from flathub
      community.general.flatpak:
        name: com.obsproject.Studio
        state: present
