---

#
# install-packages
#
# This task installs packages on the system.
#

- name: Importing RPM Fusion (free) key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: Importing RPM Fusion (non-free) key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Enable the RPM Fusion Free repository
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    update_cache: true
  when: ansible_distribution == 'Fedora'

- name: Enable the RPM Fusion Non-Free repository
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    update_cache: true
  when: ansible_distribution == 'Fedora'

# Install some back packages if the install_basic_packages variable is true
- name: Install basic packages
  when: install_basic_packages
  block:

    - name: Install basic packages
      ansible.builtin.dnf:
        name:
          - curl
          - git
          - htop
          - mozilla-openh264
          - ncdu
          - screen
          - tmux
          - tree
          - vim
          - wget
        state: present
        update_cache: true
