---

#
# extra-repos
#
# This task installs extra repos and packages on the system.
#

# Adding the flathub repo in this way seems to be broken at the moment
# https://stackoverflow.com/questions/73090882/ansible-added-flathub-repo-isnt-recognized
# https://github.com/ansible-collections/community.general/issues/3118
# - name: Add the flathub flatpak repository
#   community.general.flatpak_remote:
#     name: flathub
#     flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
#     method: system
#     state: present

- name: Add flathub repo manually
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install the Flatseal flatpak from flathub
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    state: present

# Install ProtonUp-QT if the install_protonup variable is true
- name: Install ProtonUp-QT flatpak
  when: install_protonup
  block:

    - name: Install the ProtonUp-QT flatpak from flathub
      community.general.flatpak:
        name: net.davidotek.pupgui2
        state: present

# Install Steam if the install_steam variable is true
- name: Install Steam
  when: install_steam
  block:

    - name: Install Steam
      ansible.builtin.dnf:
        name:
          - steam
          - steam-devices
          - gamemode
          - gamescope
        state: present
        update_cache: true

# Install Steam flatpak if the install_steam_flatpak variable is true
- name: Install Steam flatpak
  when: install_steam_flatpak
  block:

    - name: Install the Steam flatpak from flathub
      community.general.flatpak:
        name: com.valvesoftware.Steam
        state: present

    - name: Install Steam dependencies
      ansible.builtin.dnf:
        name:
          - steam-devices
          - gamemode
        state: present
        update_cache: true

# Install Mangohud if the install_mangohud variable is true
- name: Install Mangohud
  when: install_mangohud
  block:

    - name: Install Mangohud
      ansible.builtin.dnf:
        name:
          - mangohud
          - mangohud.i686
          - goverlay
        state: present
        update_cache: true

    - name: Create Mangohud config directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.config/MangoHud"
        state: directory
        owner: "{{ ansible_facts.env.SUDO_USER }}"
        group: "{{ ansible_facts.env.SUDO_USER }}"
        mode: 0755

    - name: Copy Mangohud config file
      ansible.builtin.copy:
        src: files/MangoHud.conf
        dest: "{{ lookup('env', 'HOME') }}/.config/MangoHud/MangoHud.conf"
        owner: "{{ ansible_facts.env.SUDO_USER }}"
        group: "{{ ansible_facts.env.SUDO_USER }}"
        mode: 0644

# Install Mangohud flatpak if the install_mangohud_flatpak variable is true
- name: Install Mangohud flatpak
  when: install_mangohud_flatpak
  block:

    - name: Install the Mangohud flatpak from flathub
      community.general.flatpak:
        name: org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
        state: present

    - name: Create Mangohud config directory within Steam flatpak
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.var/app/com.valvesoftware.Steam/config/MangoHud"
        state: directory
        owner: "{{ ansible_facts.env.SUDO_USER }}"
        group: "{{ ansible_facts.env.SUDO_USER }}"
        mode: 0755

    - name: Copy Mangohud config file into Steam flatpak
      ansible.builtin.copy:
        src: files/MangoHud.conf
        dest: "{{ lookup('env', 'HOME') }}/.var/app/com.valvesoftware.Steam/config/MangoHud/MangoHud.conf"
        owner: "{{ ansible_facts.env.SUDO_USER }}"
        group: "{{ ansible_facts.env.SUDO_USER }}"
        mode: 0644

# Install chrome if the install_chrome variable is true
- name: Install Chrome
  when: install_chrome
  block:

    - name: Import google chrome RPM GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.google.com/linux/linux_signing_key.pub

    - name: Add google chrome repo
      ansible.builtin.yum_repository:
        name: google-chrome
        description: Google Chrome RPM Repo
        baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        gpgcheck: true
        enabled: 1

    - name: Install google chrome
      ansible.builtin.dnf:
        name:
          - google-chrome-stable
        state: present
        update_cache: true

# Install Chrome flatpak if the install_chrome_flatpak variable is true
- name: Install Chrome flatpak
  when: install_chrome_flatpak
  block:

    - name: Install the Chrome flatpak from flathub
      community.general.flatpak:
        name: com.google.Chrome
        state: present

# Install thunderbird if the install_thunderbird variable is true
- name: Install Thunderbird
  when: install_thunderbird
  block:

    - name: Install Thunderbird
      ansible.builtin.dnf:
        name:
          - thunderbird
        state: present
        update_cache: true

# Install Thunderbird flatpak if the install_thunderbird_flatpak variable is true
- name: Install Thunderbird flatpak
  when: install_thunderbird_flatpak
  block:

    - name: Install the Thunderbird flatpak from flathub
      community.general.flatpak:
        name: org.mozilla.Thunderbird
        state: present

# Install vscode if the install_vscode variable is true
- name: Install VSCode
  when: install_vscode
  block:

    - name: Import vscode RPM GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add vscode repo
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: true
        enabled: 1

    - name: Install vscode
      ansible.builtin.dnf:
        name:
          - code
        state: present
        update_cache: true

# Install VSCode flatpak if the install_vscode_flatpak variable is true
- name: Install VSCode flatpak
  when: install_vscode_flatpak
  block:

    - name: Install the VSCode flatpak from flathub
      community.general.flatpak:
        name: com.visualstudio.code
        state: present

# Install keepassxc if the install_keepassxc variable is true
- name: Install KeepassXC
  when: install_keepassxc
  block:

    - name: Install keepassxc
      ansible.builtin.dnf:
        name:
          - keepassxc
        state: present
        update_cache: true

# Install KeepassXC flatpak if the install_keepassxc_flatpak variable is true
- name: Install KeepassXC flatpak
  when: install_keepassxc_flatpak
  block:

    - name: Install the KeepassXC flatpak from flathub
      community.general.flatpak:
        name: org.keepassxc.KeePassXC
        state: present

# Install OBS flatpak if the install_obs variable is true
- name: Install OBS flatpak
  when: install_obs
  block:

    - name: Install the OBS Studio flatpak from flathub
      community.general.flatpak:
        name: com.obsproject.Studio
        state: present

# Install VLC flatpak if the install_vlc variable is true
- name: Install VLC flatpak
  when: install_vlc
  block:

    - name: Install the VLC flatpak from flathub
      community.general.flatpak:
        name: org.videolan.VLC
        state: present

# Install zenpower if the install_zenpower variable is true
- name: Install Zenpower
  when: install_zenpower
  block:

    - name: Enable zenpower copr repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        name: birkch/zenpower3
        state: enabled

    - name: Install zenpower3
      ansible.builtin.dnf:
        name:
          - dkms-zenpower3
          - zenmonitor3
          - zenmonitor3-cli
        state: present
        update_cache: true

    - name: Add k10temp modprobe blacklist
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/dkms-zenpower3.conf
        line: blacklist k10temp
        create: true
        owner: root
        mode: 0644

# Install corectrl if the install_corectrl variable is true
- name: Install Corectrl
  when: install_corectrl
  block:

    - name: Install Corectrl
      ansible.builtin.dnf:
        name:
          - corectrl
        state: present
        update_cache: true

# Install kdiskmark if the install_kdiskmark variable is true
- name: Install Kdiskmark
  when: install_kdiskmark
  block:

    - name: Install kdiskmark
      ansible.builtin.dnf:
        name:
          - kdiskmark
        state: present
        update_cache: true

# Install solaar if the install_solaar variable is true
- name: Install Solaar
  when: install_solaar
  block:

    - name: Install solaar
      ansible.builtin.dnf:
        name:
          - solaar
          - solaar-udev
        state: present
        update_cache: true

# Install qemu/libvirt if the install_qemu variable is true
- name: Install QEMU and Libvirt
  when: install_qemu
  block:

    - name: Install QEMU
      ansible.builtin.dnf:
        name:
          - bridge-utils
          - genisoimage
          - guestfs-tools
          - libguestfs-tools
          - libvirt
          - libvirt-devel
          - qemu
          - qemu-kvm
          - spice-gtk-tools
          - swtpm
          - virt-install
          - virt-manager
          - virt-top
          - virt-viewer
        state: present
        update_cache: true

# Install gzdoom if the install_gzdoom variable is true
- name: Install GZDoom
  when: install_gzdoom
  block:

    - name: Enable gzdoom copr repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        name: nalika/gzdoom
        state: enabled

    - name: Install gzdoom
      ansible.builtin.dnf:
        name:
          - gzdoom
        state: present
        update_cache: true

# Install dsda-doom if the install_dsdadoom variable is true
- name: Install dsda-doom
  when: install_dsdadoom
  block:

    - name: Enable dsda-doom copr repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        name: alastortenebris/dsda-doom
        state: enabled

    - name: Install dsda-doom
      ansible.builtin.dnf:
        name:
          - dsda-doom
        state: present
        update_cache: true
