---

#
# Discord
#
# This task installs the Flatpak version of Discord
# https://flathub.org/apps/com.discordapp.Discord
#


# Install Discord flatpak if the install_discord variable is true
- name: Install Discord flatpak
  when: install_discord_flatpak
  block:

    - name: Install the Discord flatpak from flathub
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present
