---

#
# Freetube
#
# This task installs the Flatpak version of Freetube
# https://flathub.org/apps/io.freetubeapp.FreeTube
#


# Install Freetube flatpak if the install_freetube variable is true
- name: Install Freetube flatpak
  when: install_freetube_flatpak
  block:

    - name: Install the Freetube flatpak from flathub
      community.general.flatpak:
        name: io.freetubeapp.FreeTube
        state: present
