---

#
# Duckstation
#
# This task installs the Flatpak version of Duckstation
#


# Install Duckstation flatpak if the install_duckstation_flatpak variable is true
- name: Install Duckstation flatpak
  when: install_duckstation_flatpak
  block:

    - name: Install the Duckstation flatpak from flathub
      community.general.flatpak:
        name: org.duckstation.DuckStation
        state: present
