---

#
# ProtonUp-QT
#
# This task installs the Flatpak version of ProtonUp-QT
# https://flathub.org/apps/net.davidotek.pupgui2
#

# Install ProtonUp-QT if the install_protonup variable is true
- name: Install ProtonUp-QT flatpak
  when: install_protonup
  block:

    - name: Install the ProtonUp-QT flatpak from flathub
      community.general.flatpak:
        name: net.davidotek.pupgui2
        state: present
